# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 121b020b1a5c77a9759d8894f8ef30fedfafc2e19c8a27b92a23c786f2ddf757c820b3354d182dac159a950769c342472a9d014ce958891244235bd6b3f7071e

test:
  secret_key_base: c50ec08a4b3d9817f3b65dd41cf8c50358ecd98d0b96cb02450bffbe04ddbb84d675470dec70b3d04c903ffba3c2ae2f13e940a8c317cd17391282e69a3b6991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
